# Generated by Django 5.2.4 on 2025-07-20 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ports_profile_server_config_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='is_admin_instance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instances',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
