# Generated by Django 5.2.4 on 2025-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_instances_is_admin_instance_alter_instances_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='start_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
