# Generated by Django 5.2.4 on 2025-07-25 12:30

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_instances_start_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='log_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.user_logs_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='server_config',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
