# Generated by Django 5.2.4 on 2025-07-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_instances_log_file_alter_profile_server_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
