# Generated by Django 5.2.4 on 2025-07-28 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instances',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
